# pyproject.toml

[tool.ruff]
line-length = 88
preview = true

[tool.ruff.lint]
select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "C90", # mccabe complexity
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8-naming
    "D",   # pydocstyle
]
ignore = [
    "D107", # Missing docstring in `__init__`
    "D203", # 1 blank line required before class docstring (conflicts with black)
    "D212", # Multi-line docstring summary should start at the first line
    "E501", # Line too long (handled by `line-length` and black)
]

[tool.ruff.lint.per-file-ignores]
"*/__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"
