[project]
name = "openmm_fts"
description = "Examples using the string method in collective variables on alanine dipeptide in OpenMM"
version = "0.1.0"
readme = "README.md"
keywords = ["openmm", "free-energy", "string-method"]
authors = [{name = "Clay Batton", email = "cbatton35@example.com"}]
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "h5py",
    "numba",
    "mdtraj",
    "openmm",
    "openmm_csvr @ git+https://github.com/cbatton/openmm_csvr.git",
    "mpi4py",
    "gsd",
]

[project.scripts]
omm-fts = "omm_fts.scripts.run_fts:main"
omm-replica = "omm_fts.scripts.run_replica:main"
omm-convert = "omm_fts.scripts.convert_h5_to_gsd:main"
omm-interpolate-string = "omm_fts.scripts.interpolate_string:main"
omm-analyze-fe = "omm_fts.scripts.analyze_fe:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/omm_fts"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "B", "D", "E", "F", "I", "N", "W", "C4", "PL", "PT", "PIE", "PYI", "TID", "TCH", "RUF", "RSE", "ICN001",
]
ignore = [
    "N806", "PLR0911", "PLR0912", "PLR0913", "PLR0914", "PLR0915", "PLR1702",
    "D107", # Missing docstring in `__init__`
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
files = ["omm_fts"]
strict = true
pretty = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE"
